version: '3.8'
services:
  boilerack:
    build: 
      context: .
      args:
        NODE_ENV: 'development'
    container_name: boilerack
    hostname: boilerack
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app/src/
      - .env/:/app/.env
    restart: always

